language: node_js
node_js:
  - "node"

before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn run setup
  - yarn run langs

script:
  - yarn test
